### ISSUE TITLE
[BUG]Stuck in manual mode on my pi0W v1.1.0

### ISSUE THREAD

**Issue by fubastshitardck** [evilsocket/pwnagotchi#482] opened 2019-10-31 10:08 UTC
**Describe the bug**
Can't boot to auto mode.

**What I've done**
1.  I flash  v1.1.0 in my brand new sd card.
2. Add a(vim) config.yml in my /Volumes/boot; 
     add below configuration:
==================================
main:
    plugins:
        grid:
            enabled: true
ui:
    display:
        type: 'waveshare213d' 
        color: 'black'
==================================

(I use waveshare 213(B) turn out the above configuration work fine)

3.Connect the pi to its power port. Wait 30 minutes. 

4.It stay in auto mode for about 10 minutes, 
    but the screen change from 'auto 'to 'manu' automatically.

**Expected behavior**

I expect it to stay in auto mode since I only plug the power port of my rpi0W

**Screenshots**

**Environment (please complete the following information):**
 - v1.1.0
 - mac OS
 - rpi0W
 - waveshare 213b

**Comment by evilsocket** [comment] 2019-10-31 11:47
duplicate of #482

**Closed by evilsocket** 2019-10-31 11:47 UTC
Labels: bug

**Comment by fubastshitardck** [comment] 2019-10-31 12:10
thank you! you are awesome!
